### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by javisth** [ClintRen/yolov5_convert_weight_to_coreml#2]
When I run this command : python convert.py --yolov5-repo /path/to/yolov5 --weight yolov5s.pt --img-size 640 --quantize
I get an error     import models
ModuleNotFoundError: No module named 'models' in the convert.py file.

**Comment by ClintRen** [comment]
> When I run this command : python convert.py --yolov5-repo /path/to/yolov5 --weight yolov5s.pt --img-size 640 --quantize
> 
> I get an error     import models
> 
> ModuleNotFoundError: No module named 'models' in the convert.py file.

You should specify the actual path of the yolov5 folder.
